apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local
  namespace: k8sgpt-operator-system
spec:
  ai:
    # autoRemediation:
    # enabled: true
    # similarityRequirement: "90"
    # resources:
    #   - Pod
    #   - Service
    #   - Deployment
    enabled: false
    backend: localai
    baseUrl: http://ollama.ollama.svc.cluster.local:11434
    model: llama2
    language: english
  analysis:
    interval: "5m"  # Set analysis interval to 5 minutes
  noCache: false
  version: v0.3.41